# Generated by Django 5.0.2 on 2024-04-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateModel',
            new_name='Update',
        ),
    ]
