# Generated by Django 5.0.2 on 2024-04-16 07:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_update_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content'),
        ),
    ]
