# Generated by Django 5.0.2 on 2024-04-22 11:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0004_alter_update_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
