# Generated by Django 5.0.1 on 2024-03-06 10:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
