# Generated by Django 5.0.2 on 2024-03-12 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(default=True, null=True, upload_to='images/us/')),
                ('image2', models.ImageField(default=True, null=True, upload_to='images/us/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='content',
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='us.contact')),
            ],
        ),
    ]
