# Generated by Django 5.0.2 on 2024-04-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image2',
        ),
        migrations.AlterField(
            model_name='contact',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='us/contact/'),
        ),
    ]
