# Generated by Django 5.0.2 on 2024-04-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_remove_contact_image2_alter_contact_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='type_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
