# Generated by Django 5.0.2 on 2024-04-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0003_url_type_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='us/icons/'),
        ),
    ]
