# Generated by Django 5.0.2 on 2024-03-19 11:15

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('NAMAZ TRAINING', 'NAMAZ TRAINING'), ('ABOUT ISLAM', 'ABOUT_ISLAM'), ('INSPIRATIONAL STORIES', 'INSPIRATIONAL STORIES'), ('ABOUT QURAN', 'ABOUT QURAN'), ('QURAN LEANING', 'QURAN LEANING')], default='NAMAZ TRAINING', max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('audio', models.FileField(blank=True, max_length=255, null=True, upload_to='audio/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GhuslAndTaharat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('audio', models.FileField(blank=True, max_length=255, null=True, upload_to='audio/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Namaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namaz_type', models.CharField(choices=[('FAJR', 'FAJR'), ('ZUHR', 'ZUHR'), ('ASR', 'ASR'), ('MAGHREB', 'MAGHREB'), ('ISHA', 'ISHA'), ('VITR', 'VITR')], default='FAJR', max_length=255)),
                ('explanation_text', models.CharField(max_length=255)),
                ('sura_text', models.TextField()),
                ('audio', models.FileField(max_length=255, upload_to='audio/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NamazImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='namaz/')),
                ('namaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='education.namaz')),
            ],
        ),
    ]
