# Generated by Django 5.0.2 on 2024-03-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namaz',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='namaz',
            name='audio',
            field=models.FileField(default=None, upload_to='audio/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='ghuslandtaharat',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
