# Generated by Django 5.0.2 on 2024-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namaz',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
