# Generated by Django 5.0.2 on 2024-03-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_namaz_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namaz',
            old_name='explanation_text',
            new_name='prayer_part1',
        ),
        migrations.RemoveField(
            model_name='namaz',
            name='sura_text',
        ),
        migrations.AddField(
            model_name='namaz',
            name='arab',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='namaz',
            name='prayer_part2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='namaz',
            name='transcription',
            field=models.TextField(default=''),
        ),
    ]
