# Generated by Django 5.0.2 on 2024-03-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_namaz_audio_file_namaz_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghuslandtaharat',
            name='audio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='namaz',
            name='audio',
            field=models.FileField(max_length=255, upload_to='audio/'),
        ),
    ]
