# Generated by Django 5.0.2 on 2024-03-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_ghuslandtaharat_audio_alter_namaz_audio'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namaz',
            name='photo',
        ),
        migrations.AddField(
            model_name='namaz',
            name='images',
            field=models.ManyToManyField(max_length=255, related_name='namaz_images', to='image.image'),
        ),
        migrations.AlterField(
            model_name='education',
            name='audio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='audio/'),
        ),
    ]
