# Generated by Django 5.0.2 on 2024-03-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_rename_explanation_text_namaz_prayer_part1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namaz',
            name='gender',
            field=models.CharField(default='male', max_length=255),
        ),
    ]
