# Generated by Django 5.0.2 on 2024-03-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_namaz_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamazBegin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namaz_type', models.CharField(choices=[('FAJR', 'FAJR'), ('ZUHR', 'ZUHR'), ('ASR', 'ASR'), ('MAGHREB', 'MAGHREB'), ('ISHA', 'ISHA'), ('VITR', 'VITR')], default='FAJR', max_length=255)),
                ('gender', models.CharField(default='male', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('prayer_part1', models.CharField(max_length=255)),
                ('prayer_part2', models.TextField()),
                ('mentally', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='namaz/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='namaz',
            name='arab',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='namaz',
            name='prayer_part2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='namaz',
            name='transcription',
            field=models.TextField(),
        ),
    ]
