# Generated by Django 5.0.2 on 2024-04-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_delete_namazbegin_namaz_description_namaz_mentally_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='education',
            name='content',
        ),
        migrations.RemoveField(
            model_name='education',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='EducationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='education/')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='education.education')),
            ],
        ),
    ]
