# Generated by Django 5.0.2 on 2024-04-04 03:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_remove_education_audio_remove_education_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ghusl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Taharat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('audio', models.FileField(blank=True, max_length=255, null=True, upload_to='audio/')),
            ],
        ),
        migrations.DeleteModel(
            name='GhuslAndTaharat',
        ),
    ]
