# Generated by Django 5.0.2 on 2024-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_ghusl_content_alter_taharat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationcategory',
            name='day',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'DEFAULT'), ('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], default='DEFAULT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationcategory',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationcategory',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
